# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/centos-7"
    #master.vm.hostname = "master"
    master.vm.provider "vmware_workstation" do |v|
	  v.gui = true
      v.vmx["name"] = "master"
	  v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
	  v.vmx["ethernet0.pcislotnumber"] = "32"
    end
    master.vm.provision :shell do |shell|
      shell.path = "install_kubernetes.sh"
      shell.args = ["master", "192.168.99.10"]
    end
  end
  workers=1
  ram_worker=2048
  cpu_worker=2
  (1..workers).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "bento/centos-7"
      #worker.vm.hostname = "worker#{i}"
      worker.vm.provider "vmware_workstation" do |v|
		v.gui = true
		v.vmx["name"] = "worker#{i}"
        v.vmx["memsize"] = ram_worker
		v.vmx["numvcpus"] = cpu_worker
		v.vmx["ethernet0.pcislotnumber"] = "32"
      end
      worker.vm.provision :shell do |shell|
        shell.path = "install_kubernetes.sh"
        shell.args = ["node", i]
      end
    end
  end
end
